### ISSUE TITLE
I am using Mac M1, without CUDA. How to make it work 

### ISSUE THREAD

**Issue by jeanffee** [yardenfren1996/B-LoRA#12]
Without cuda, in the end of training process, I got this error message. I checked online, it says because I don't have CUDA. How to avoid? thanks!

Traceback (most recent call last):
  File "/Users/jingfeng/Code/ai/B-LoRA/train_dreambooth_b-lora_sdxl.py", line 2029, in <module>
    main(args)
  File "/Users/jingfeng/Code/ai/B-LoRA/train_dreambooth_b-lora_sdxl.py", line 1771, in main
    optimizer.step()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/accelerate/optimizer.py", line 170, in step
    self.optimizer.step(closure)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/torch/optim/lr_scheduler.py", line 75, in wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/torch/optim/optimizer.py", line 391, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/bitsandbytes/optim/optimizer.py", line 263, in step
    self.update_step(group, p, gindex, pindex)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/bitsandbytes/optim/optimizer.py", line 504, in update_step
    F.optimizer_update_8bit_blockwise(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/bitsandbytes/functional.py", line 952, in optimizer_update_8bit_blockwise
    str2optimizer8bit_blockwise[optimizer_name][0](
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'str2optimizer8bit_blockwise' is not defined
Steps:   0%|                                                                                                                                       | 0/1000 [01:31<?, ?it/s]
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1082, in launch_command
    simple_launcher(args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/accelerate/commands/launch.py", line 688, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/homebrew/Caskroom/miniforge/base/envs/py311/bin/python3.11', 'train_dreambooth_b-lora_sdxl.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--instance_data_dir=/Users/jingfeng/Code/ai/B-LoRA/input', '--output_dir=output', '--instance_prompt=A [v]', '--resolution=1024', '--rank=64', '--train_batch_size=1', '--learning_rate=5e-5', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=1000', '--checkpointing_steps=500', '--seed=0', '--gradient_checkpointing', '--use_8bit_adam', '--mixed_precision=no']' returned non-zero exit status 1.

**Comment by jeanffee** [comment]
error message is resolved after doing this(GPT remind me to do so):
    pip install bitsandbytes --upgrade

but then another error pop up:
06/02/2024 12:25:41 - INFO - __main__ -   Total optimization steps = 1000
Steps:   0%|                                                                                                                                       | 0/1000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Users/jingfeng/Code/ai/B-LoRA/train_dreambooth_b-lora_sdxl.py", line 2029, in <module>
    main(args)
  File "/Users/jingfeng/Code/ai/B-LoRA/train_dreambooth_b-lora_sdxl.py", line 1771, in main
    optimizer.step()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/accelerate/optimizer.py", line 170, in step
    self.optimizer.step(closure)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/torch/optim/lr_scheduler.py", line 75, in wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/torch/optim/optimizer.py", line 391, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/bitsandbytes/optim/optimizer.py", line 269, in step
    self.update_step(group, p, gindex, pindex)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/bitsandbytes/optim/optimizer.py", line 517, in update_step
    F.optimizer_update_8bit_blockwise(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/bitsandbytes/functional.py", line 1395, in optimizer_update_8bit_blockwise
    prev_device = pre_call(g.device)
                  ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/bitsandbytes/functional.py", line 416, in pre_call
    prev_device = torch.cuda.current_device()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/torch/cuda/__init__.py", line 778, in current_device
    _lazy_init()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/torch/cuda/__init__.py", line 284, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Steps:   0%|                                                                                                                                       | 0/1000 [01:27<?, ?it/s]
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1082, in launch_command
    simple_launcher(args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/accelerate/commands/launch.py", line 688, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/homebrew/Caskroom/miniforge/base/envs/py311/bin/python3.11', 'train_dreambooth_b-lora_sdxl.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--instance_data_dir=/Users/jingfeng/Code/ai/B-LoRA/input', '--output_dir=output', '--instance_prompt=A [v]', '--resolution=1024', '--rank=64', '--train_batch_size=1', '--learning_rate=5e-5', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=1000', '--checkpointing_steps=500', '--seed=0', '--gradient_checkpointing', '--use_8bit_adam', '--mixed_precision=no']' returned non-zero exit status 1.

**Comment by weihui1308** [comment]
I solveed this: NameError: name 'str2optimizer8bit_blockwise' is not defined

by: pip install bitsandbytes --upgrade
